import { BaseRequestOptions } from './shared';

/**
 * The format in which the generated images are returned
 */
export type ImageResponseFormat = 'url' | 'b64_json';

/**
 * The size of the generated images
 */
export type ImageSize = '256x256' | '512x512' | '1024x1024' | '1792x1024' | '1024x1792';

/**
 * The quality of the generated images
 */
export type ImageQuality = 'standard' | 'hd';

/**
 * The style of the generated images
 */
export type ImageStyle = 'vivid' | 'natural';

/**
 * Parameters for creating an image
 */
export interface ImageCreateParams extends BaseRequestOptions {
  /**
   * The model to use for image generation
   */
  model: string;
  
  /**
   * A text description of the desired image(s)
   */
  prompt: string;
  
  /**
   * The number of images to generate. Must be between 1 and 10
   */
  n?: number;
  
  /**
   * The quality of the image that will be generated
   */
  quality?: ImageQuality;
  
  /**
   * The format in which the generated images are returned
   */
  response_format?: ImageResponseFormat;
  
  /**
   * The size of the generated images
   */
  size?: ImageSize;
  
  /**
   * The style of the generated images
   */
  style?: ImageStyle;
  
  /**
   * A unique identifier representing your end-user
   */
  user?: string;
}

/**
 * Represents the url or the content of an image generated by the OpenAI API
 */
export interface Image {
  /**
   * The base64-encoded JSON of the generated image, if response_format is b64_json
   */
  b64_json?: string;
  
  /**
   * The URL of the generated image, if response_format is url (default)
   */
  url?: string;
  
  /**
   * The prompt that was used to generate the image, if there was any revision to the prompt
   */
  revised_prompt?: string;
}

/**
 * Represents a response from the image generation endpoint
 */
export interface ImagesResponse {
  /**
   * The Unix timestamp (in seconds) of when the image was created
   */
  created: number;
  
  /**
   * The list of generated images
   */
  data: Image[];
}